version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)-8s [%(threadName)s] %(name)s %(filename)s: %(lineno)d: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: cloghandler.ConcurrentRotatingFileHandler
    filename: ./Debug/logs/running.log
    level: INFO
    formatter: simple
    encoding: UTF-8
    maxBytes: 1024 * 1024 * 10
    delay: True
    backupCount: 50
root:
  level: INFO
  handlers: [file]