version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)-8s [%(threadName)s] %(name)s %(filename)s: %(lineno)d: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file_linux:
    class: cloghandler.ConcurrentRotatingFileHandler
    filename: ./Debug/logs/running.log
    level: INFO
    formatter: simple
    encoding: UTF-8
    maxBytes: 10485760
    delay: True
    backupCount: 50
  file_windows:
    class: logging.handlers.TimedRotatingFileHandler
    filename: ./Debug/logs/running.log
    level: INFO
    formatter: simple
    encoding: UTF-8
    when: d
    interval: 1
    backupCount: 30
root:
  level: INFO
  handlers: [file_windows]